language: ruby
dist: xenial
branches:
  only:
    - master
    - staging
    - trying
    - /^[\d.]+$/
    - /.+-stable$/
env:
  - "TEST_TOOL=rubygems YAML=psych"
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
jobs:
  include:
    - stage: linting
      rvm: 2.6
      env:
        - "TEST_TOOL=rubygems YAML=psych"
      script: util/ci rubocop
stages:
  - test
before_script:
  - util/ci before_script
script:
  - util/ci script
